[snowflake]
account = "XA20133"             # whatever your account locator is
user = "harshawilson"                    # or ACME, WDE user depending on the app
password = "HarshaWilson1*"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
